name: Run History Bot

on:
  schedule:
    - cron: '0 8,18 * * *'  # 8:00 и 18:00 UTC
  workflow_dispatch:

jobs:
  run-history-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt

    - run: |
        mkdir -p public/
        echo "[]" > seen_ids1.txt  # Создаём seen_ids1.txt в корне
        python bot/history.py
        ls -la public/
        git status
      env:
        TELEGRAM_HISTORY_TOKEN: ${{ secrets.TELEGRAM_HISTORY_TOKEN }}

    - run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Stah2024/newsforsvoi
        git add public/history.html public/history_rss.xml public/sitemap.xml
        git commit -m "Update history files [skip ci]" || echo "Нет изменений"
        git push
      env:
        GH_PAT: ${{ secrets.GH_PAT }}