name: Run History Bot

on:
  schedule:
    - cron: '0 8,18 * * *'  # 8:00 и 18:00 UTC
  workflow_dispatch:

jobs:
  run-history-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_HISTORY_TOKEN: ${{ secrets.TELEGRAM_HISTORY_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt

    - name: Run bot script
      run: |
        mkdir -p public/
        touch seen_ids1.txt
        python bot/history.py
        ls -la public/
        git status

    - name: Commit and push updated files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Stah2024/newsforsvoi

        find public/ -type f -name "*.html" -o -name "*.xml" | xargs git add
        git add seen_ids1.txt || echo "Нет изменений"
        git commit -m "Update history files [skip ci]" || echo "Нет изменений"
        git push origin main || echo "Push не удался"