name: Run History Bot

on:
  schedule:
    - cron: '0 8,18 * * *'  # Запуск в 08:00 и 18:00 CEST (10:00 и 20:00 MSK)
  workflow_dispatch:        # Возможность ручного запуска вручную

jobs:
  run-history-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 🔥 Отключает github-actions[bot]

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r bot/requirements.txt

    - name: Run history.py
      env:
        TELEGRAM_HISTORY_TOKEN: ${{ secrets.TELEGRAM_HISTORY_TOKEN }}
      run: |
        python bot/history.py

    - name: Commit updated files
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add public/history.html public/media/*
        git commit -m "Update history.html and media files from history bot [skip ci]" || echo "No changes"
        git push 